version: '3'

services:
  mongo:
    image: mongo:3.4
    networks:
      default:
        aliases:
          - mongo
    volumes:
      - ./mdb/mongodata:/data/db
    ports:
      - "27017:27017"
  backend:
    build:
      context: .
      dockerfile: dockerbuild/Dockerfile-backend
    image: mvartak/modeldb-backend:latest
    networks:
      default:
        aliases:
          - backend
    volumes:
      - ./mdb/sqlitedata:/db
    ports:
      - "6543:6543"
  frontend:
    build:
      context: .
      dockerfile: dockerbuild/Dockerfile-frontend
    image: mvartak/modeldb-frontend:latest
    networks:
      default:
        aliases:
          - frontend
    ports:
      - "3000:3000"