apiVersion: v1
kind: Service
metadata:
  name: modeldb-frontend
  labels:
    app: modeldb
spec:
  ports:
    - port: 3000
  selector:
    app: modeldb
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: modeldb-frontend
  labels:
    app: modeldb
spec:
  selector:
    matchLabels:
      app: modeldb
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modeldb
        tier: frontend
    spec:
      containers:
      - image: mitdbg/modeldb-frontend
        name: frontend
        env:
        - name: BACKEND_HOST
          value: modeldb-backend
        ports:
        - containerPort: 3000
          name: frontend
