apiVersion: v1
kind: Service
metadata:
  name: modeldb-backend
  labels:
    app: modeldb
spec:
  ports:
    - port: 6543
  selector:
    app: modeldb
    tier: backend
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pv-claim
  labels:
    app: modeldb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: modeldb-backend
  labels:
    app: modeldb
spec:
  selector:
    matchLabels:
      app: modeldb
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modeldb
        tier: backend
    spec:
      containers:
      - image: mvartak/modeldb-backend
        name: modeldb
        env:
          - name: MONGO_HOST
            value: modeldb-mongodb
        ports:
        - containerPort: 6543
          name: modeldb
        volumeMounts:
        - name: modeldb-persistent-storage
          mountPath: /db
      volumes:
      - name: modeldb-persistent-storage
        persistentVolumeClaim:
          claimName: backend-pv-claim
