apiVersion: v1
kind: Service
metadata:
  name: modeldb-mongodb
  labels:
    app: modeldb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: modeldb
    tier: mongodb
  # clusterIP: None
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
  labels:
    app: modeldb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: modeldb-mongodb
  labels:
    app: modeldb
spec:
  selector:
    matchLabels:
      app: modeldb
      tier: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modeldb
        tier: mongodb
    spec:
      containers:
      - image: mongo:3.4
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
